# Generated by Django 5.1.3 on 2025-10-14 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('incident_type', models.CharField(choices=[('theft', 'Theft'), ('murder', 'Murder'), ('abuse', 'Child Abuse'), ('accident', 'Accident')], max_length=20)),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('incident_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ob_number', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
    ]
