# Generated by Django 5.1.3 on 2025-10-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0002_statement_service_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='incident_evidence',
            field=models.FileField(default='', upload_to='evidence/'),
            preserve_default=False,
        ),
    ]
