# Generated by Django 5.2.7 on 2025-10-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0004_crime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crime',
        ),
    ]
